### PR TITLE
Remove old cruft and reduce dependences

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
@frankschae do you know what's going on with the callback tests there?

**Comment by frankschae** [comment]
There is one condition https://github.com/SciML/DiffEqSensitivity.jl/blob/bc83f240da4ffa152250a6825e8781f089609c9c/src/callback_tracking.jl#L193 that I had to add in an earlier version which is related to InterpolatingAdjoint adjoints saving behavior with `checkpointing=true` basically it just lifts the state from one limit to the other..). At some point, it was correct to remove it -- meaning tests were passing without it. I am not sure what changed this behaviour now..

**Comment by ChrisRackauckas** [comment]
I'm curious how come removing these dependencies would cause a difference there. That's a little odd.

**Comment by frankschae** [comment]
I compared with the output from https://github.com/SciML/DiffEqSensitivity.jl/pull/597 (green). Maybe Interpolations?
```diff 
1c1
<     Testing DiffEqSensitivity
---
>      Testing DiffEqSensitivity
3,4c3,4
< └ @ Pkg.Operations /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.7/Pkg/src/Operations.jl:1488
<       Status `/tmp/jl_2jalYs/Project.toml`
---
> └ @ Pkg.Operations /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.7/Pkg/src/Operations.jl:1488
>       Status `/tmp/jl_Sfi1Ca/Project.toml`
17c17,18
<   [41bf760c] DiffEqSensitivity v6.77.0 `/cache/build/default-power8bot1-0/julialang/diffeqsensitivity-dot-jl`
---
>   [9fdde737] DiffEqOperators v4.43.0
>   [41bf760c] DiffEqSensitivity v6.76.0 `/cache/build/default-armageddon-7/julialang/diffeqsensitivity-dot-jl`
21a23
>   [7a1cc6ca] FFTW v1.4.6
25a28
>   [af5da776] GlobalSensitivity v1.3.3
33a37
>   [8a4e6c94] QuasiMonteCarlo v0.2.7
35c39
<   [731186ca] RecursiveArrayTools v2.29.2
---
>   [731186ca] RecursiveArrayTools v2.29.1
49a54
>   [1a1011a3] SharedArrays `@stdlib/SharedArrays`
53c58
<       Status `/tmp/jl_2jalYs/Manifest.toml`
---
>       Status `/tmp/jl_Sfi1Ca/Manifest.toml`
59c64
<   [4fba245c] ArrayInterface v6.0.14
---
>   [4fba245c] ArrayInterface v6.0.12
64a70,71
>   [4c555306] ArrayLayouts v0.8.6
>   [13072b0f] AxisAlgorithms v1.0.1
65a73
>   [aae01518] BandedMatrices v0.17.0
66a75,76
>   [8e7c35d0] BlockArrays v0.16.17
>   [ffab5731] BlockBandedMatrices v0.11.6
76c86
<   [38540f10] CommonSolve v0.2.1
---
>   [38540f10] CommonSolve v0.2.0
79a90
>   [b152e2b5] CompositeTypes v0.1.2
92c103,104
<   [41bf760c] DiffEqSensitivity v6.77.0 `/cache/build/default-power8bot1-0/julialang/diffeqsensitivity-dot-jl`
---
>   [9fdde737] DiffEqOperators v4.43.0
>   [41bf760c] DiffEqSensitivity v6.76.0 `/cache/build/default-armageddon-7/julialang/diffeqsensitivity-dot-jl`
97a110
>   [5b8099bc] DomainSets v0.5.9
102a116
>   [7a1cc6ca] FFTW v1.4.6
113a128
>   [af5da776] GlobalSensitivity v1.3.3
119a135,136
>   [a98d9a8b] Interpolations v0.13.6
>   [8197267c] IntervalSets v0.5.4
125a143
>   [5ab0869b] KernelDensity v0.6.3
130c148,152
<   [10f19ff3] LayoutPointers v0.1.9
---
>   [a5e1c1ea] LatinHypercubeSampling v1.8.0
>   [73f95e8e] LatticeRules v0.0.1
>   [10f19ff3] LayoutPointers v0.1.8
>   [5078a376] LazyArrays v0.22.10
>   [d7e5e226] LazyBandedMatrices v0.7.16
140a163
>   [a3b82374] MatrixFactorizations v0.9.1
150c173
<   [6fe1bfb0] OffsetArrays v1.12.2
---
>   [6fe1bfb0] OffsetArrays v1.12.1
168a192
>   [8a4e6c94] QuasiMonteCarlo v0.2.7
170a195
>   [c84ed2f1] Ratios v0.4.3
173c198
<   [731186ca] RecursiveArrayTools v2.29.2
---
>   [731186ca] RecursiveArrayTools v2.29.1
179a205
>   [7e49a35a] RuntimeGeneratedFunctions v0.5.3
187a214
>   [ed01d8cd] Sobol v1.5.0
190a218
>   [860ef19b] StableRNGs v1.0.0
205a234
>   [592b5752] Trapz v2.0.3
210a240
>   [efce3f68] WoodburyMatrices v0.5.5
213a244,245
>   [f5851436] FFTW_jll v3.3.10+0
>   [1d5cc7b8] IntelOpenMP_jll v2018.0.3+2
214a247
>   [856f044c] MKL_jll v2022.0.0+0
223a257
>   [7b1f6079] FileWatching `@stdlib/FileWatching`
263,265d296
< Precompiling project...
<   ✓ DelayDiffEq
<   1 dependency successfully precompiled in 14 seconds (170 already precompiled)
267,278d297
< ┌ Warning: OrcV2 initialization failed with
< │   err = LLVM error: No callback manager available for powerpc64le-unknown-linux-gnu
< └ @ Enzyme.Compiler.JIT /cache/julia-buildkite-plugin/depots/ea52448d-f230-4619-b27a-2d98107bd215/packages/Enzyme/7MHm8/src/compiler/orcv2.jl:103
< ┌ Warning: `vendor()` is deprecated, use `BLAS.get_config()` and inspect the output instead
< │   caller = get_blas_symbols() at validation.jl:41
< └ @ Enzyme.Compiler.FFI.BLASSupport /cache/julia-buildkite-plugin/depots/ea52448d-f230-4619-b27a-2d98107bd215/packages/Enzyme/7MHm8/src/compiler/validation.jl:41
< ┌ Warning: OrcV2 initialization failed with
< │   err = LLVM error: No callback manager available for powerpc64le-unknown-linux-gnu
< └ @ Enzyme.Compiler.JIT /cache/julia-buildkite-plugin/depots/ea52448d-f230-4619-b27a-2d98107bd215/packages/Enzyme/7MHm8/src/compiler/orcv2.jl:103
< ┌ Warning: `vendor()` is deprecated, use `BLAS.get_config()` and inspect the output instead
< │   caller = get_blas_symbols() at validation.jl:41
< └ @ Enzyme.Compiler.FFI.BLASSupport /cache/julia-buildkite-plugin/depots/ea52448d-f230-4619-b27a-2d98107bd215/packages/Enzyme/7MHm8/src/compiler/validation.jl:41
281c300
< └ @ Core /cache/build/default-power8bot1-0/julialang/diffeqsensitivity-dot-jl/src/hasbranching.jl:13
---
> └ @ Core /cache/build/default-armageddon-7/julialang/diffeqsensitivity-dot-jl/src/hasbranching.jl:13
```

**Comment by ChrisRackauckas** [comment]
Interpolations.jl wasn't removed though. The only thing that could have this kind of effect is type-piracy anyways.

**Comment by ChrisRackauckas** [comment]
Unless master is failing.

**Pull request merged**
