### PR TITLE
replace NoiseGrid by NoiseWrapper

### PR DESCRIPTION
**Pull request by frankschae**
Replaces all calls to `NoiseGrid` by `NoiseWrapper`, see https://github.com/SciML/DiffEqSensitivity.jl/issues/253 + https://github.com/SciML/DiffEqSensitivity.jl/issues/253

### CODE REVIEW

**Comment by frankschae** [comment]
InterpolatingAdjoint became much slower -- but it still executes locally without any errors (fourth line is the one which failed on Travis). I'll check why it takes much longer. Maybe it is because while `NoiseGrid` only stored the time points with their associated noise values in each interval, NoiseWrapper stores the entire process in `source`.  
```
[ Info: SDE Non-Diagonal Noise Adjoints

[ Info: [0.736545474290214 0.6809015165765869 0.5373209107227818 0.4991686900379727]
[ Info: [0.736545474290214 0.6809015165765869 0.5373209107227818 0.4991686900379727]
[ Info: [0.736545474290214 0.6809015165765869 0.5373209107227818 0.4991686900379727]
[ Info: [0.736545384426385 0.6809014328620033 0.5373207511401008 0.499168541442926]
```

**Comment by ChrisRackauckas** [comment]
The way that new values have to get added to the Brownian process is probably really slow on memory. Can you profile it and see what you find? There should be like an `insert at` which essentially ends up being an O(n) data movement, which is really bad. `NoiseGrid` might effectively be better because of that, though with less accuracy because of how it's interpolating linearly instead of respecting the variance of the Brownian bridge (but linear is the mean, so it's good). Having an option here would probably be good, with a default to maybe NoiseGrid if it's accurate enough.


[What we should probably do is abstract the interface a little bit more, so that any noise process can be used. I.e. `reversenoise!(noise)` returns a NoiseWrapper if it's a NoiseProcess, returns a reversed NoiseGrid if the input was a NoiseGrid, if it's a NoiseFunction then it just returns the original, etc. ]

**Comment by frankschae** [comment]
Is there a way to improve the speed at the first compilation?

I find that `InterpolatingAdjoint` (e.g., 
 `res_sde_u0a, res_sde_pa = @time adjoint_sensitivities(soloop,EulerHeun(),dg!,Array(t)
    ,dt=dtnd,adaptive=false,sensealg=InterpolatingAdjoint(noise=DiffEqSensitivity.ZygoteNoise()))`
) takes 
99.663339 seconds (288.24 M allocations: 100.984 GiB, 15.38% gc time)
when it is run the first time but afterwards it only takes ~0.05s ( 0.047974 seconds (921.68 k allocations: 39.726 MiB)). While the first compilation is almost 10 times slower than a similar `BacksolveAdjoint`
11.399672 seconds (33.75 M allocations: 7.513 GiB, 11.45% gc time)
the runs afterwards have almost the same speed ~ 0.04s (0.043630 seconds (855.80 k allocations: 35.445 MiB))

**Comment by ChrisRackauckas** [comment]
A huge amount of it will be covered by https://github.com/JuliaLang/www.julialang.org/pull/794 , so I wouldn't worry about it for now and just carry forward thinking it'll get fixed to a large extent.

**Comment by ChrisRackauckas** [comment]
Merged this, but Github is being weird.

**Pull request closed without merging**
