### PR TITLE
Test Enzyme v0.7

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
@frankschae can you reproduce this?

**Comment by frankschae** [comment]
yep, I can reproduce it but only when I use 
```
 julia --project=. -e 'using Pkg; Pkg.resolve(); Pkg.test()'
```
if I `dev` DiffEqSensitivity, check out this branch, and add the other package dependencies manually, it doesn't fail. (i.e., even with Enzyme 0.7)

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/DiffEqSensitivity.jl/pull/449/checks?check_run_id=3161055670#step:6:32 that might be the culprit.

**Comment by ChrisRackauckas** [comment]
what's the difference between the packages in those two cases? Can you copy-paste your print out?

**Comment by frankschae** [comment]
Yep, so if I add `OrdinaryDiffEq` to the `DiffEqSensitivity` package (this uses the OrdinaryDiffEq version v.5.60.1 as in the second case that worked from above) 
```

(DiffEqSensitivity) pkg> add OrdinaryDiffEq
    Updating registry at `~/.julia/registries/General`
   Resolving package versions...
   Installed ThreadingUtilities ─ v0.4.6
   Installed Polyester ────────── v0.3.7
   Installed StrideArraysCore ─── v0.1.17
    Updating `~/.julia/dev/DiffEqSensitivity/Project.toml`
  [1dea7af3] + OrdinaryDiffEq v5.60.1
    Updating `~/.julia/dev/DiffEqSensitivity/Manifest.toml`
  [0e44f5e4] + Hwloc v2.0.0
  [d125e4d3] + ManualMemory v0.1.4
  [1dea7af3] ↑ OrdinaryDiffEq v5.55.1 ⇒ v5.60.1
  [f517fe37] + Polyester v0.3.7
  [7792a7ef] + StrideArraysCore v0.1.17
  [8290d209] + ThreadingUtilities v0.4.6
  [3d5dd08c] + VectorizationBase v0.20.25
  [e33a78d0] + Hwloc_jll v2.5.0+0
Precompiling project...
  7 dependencies successfully precompiled in 91 seconds (121 already precompiled)
```
the tests are fine:
```
(DiffEqSensitivity) pkg> test
     Testing DiffEqSensitivity
      Status `/tmp/jl_Ydajn9/Project.toml`
  [79e6a3ab] Adapt v3.3.1
  [2169fc97] AlgebraicMultigrid v0.4.0
  [4fba245c] ArrayInterface v3.1.18
  [49dc2e85] Calculus v0.5.1
  [7057c7e9] Cassette v0.3.7
  [d360d2e6] ChainRulesCore v0.10.13
  [b0b7db55] ComponentArrays v0.11.1
  [2b5f629d] DiffEqBase v6.69.1
  [459566f4] DiffEqCallbacks v2.16.1
  [77a26b50] DiffEqNoiseProcess v5.9.0
  [41bf760c] DiffEqSensitivity v6.55.3 `~/ownCloud/Private/JSoC2021/OtherIssues/Enzyme/DiffEqSensitivity`
  [b552c78f] DiffRules v1.0.2
  [31c24e10] Distributions v0.25.11
  [7da242da] Enzyme v0.7.0
  [7a1cc6ca] FFTW v1.4.3
  [6a86dc24] FiniteDiff v2.8.1
  [f6369f11] ForwardDiff v0.10.18
  [af5da776] GlobalSensitivity v1.1.0
  [2774e3e8] NLsolve v4.5.1
  [1dea7af3] OrdinaryDiffEq v5.60.1
  [d96e819e] Parameters v0.12.2
  [1fd47b50] QuadGK v2.4.1
  [8a4e6c94] QuasiMonteCarlo v0.2.3
  [e6cf234a] RandomNumbers v1.4.0
  [731186ca] RecursiveArrayTools v2.16.0
  [189a3867] Reexport v1.1.0
  [ae029012] Requires v1.1.3
  [37e2e3b7] ReverseDiff v1.9.0
  [1bc83da4] SafeTestsets v0.0.1
  [9672c7b4] SteadyStateDiffEq v1.6.4
  [789caeaf] StochasticDiffEq v6.35.0
  [9f7883ad] Tracker v0.2.16
  [e88e6eb3] Zygote v0.6.17
  [700de1a5] ZygoteRules v0.2.1
  [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`
  [44cfe95a] Pkg `@stdlib/Pkg`
  [9a3f8284] Random `@stdlib/Random`
  [1a1011a3] SharedArrays `@stdlib/SharedArrays`
  [2f01184e] SparseArrays `@stdlib/SparseArrays`
  [10745b16] Statistics `@stdlib/Statistics`
  [8dfed614] Test `@stdlib/Test`
      Status `/tmp/jl_Ydajn9/Manifest.toml`
  [621f4979] AbstractFFTs v1.0.1
  [79e6a3ab] Adapt v3.3.1
  [2169fc97] AlgebraicMultigrid v0.4.0
  [ec485272] ArnoldiMethod v0.1.0
  [4fba245c] ArrayInterface v3.1.18
  [13072b0f] AxisAlgorithms v1.0.0
  [fa961155] CEnum v0.4.1
  [49dc2e85] Calculus v0.5.1
  [7057c7e9] Cassette v0.3.7
  [082447d4] ChainRules v0.8.23
  [d360d2e6] ChainRulesCore v0.10.13
  [38540f10] CommonSolve v0.2.0
  [bbf7d656] CommonSubexpressions v0.3.0
  [34da2185] Compat v3.31.0
  [aa819f21] CompatHelper v1.18.6
  [b0b7db55] ComponentArrays v0.11.1
  [187b0558] ConstructionBase v1.3.0
  [9a962f9c] DataAPI v1.7.0
  [864edb3b] DataStructures v0.18.9
  [e2d170a0] DataValueInterfaces v1.0.0
  [2b5f629d] DiffEqBase v6.69.1
  [459566f4] DiffEqCallbacks v2.16.1
  [c894b116] DiffEqJump v6.15.1
  [77a26b50] DiffEqNoiseProcess v5.9.0
  [41bf760c] DiffEqSensitivity v6.55.3 `~/ownCloud/Private/JSoC2021/OtherIssues/Enzyme/DiffEqSensitivity`
  [163ba53b] DiffResults v1.0.3
  [b552c78f] DiffRules v1.0.2
  [b4f34e82] Distances v0.10.3
  [31c24e10] Distributions v0.25.11
  [ffbed154] DocStringExtensions v0.8.5
  [7da242da] Enzyme v0.7.0
  [d4d017d3] ExponentialUtilities v1.8.4
  [e2ba6199] ExprTools v0.1.6
  [7a1cc6ca] FFTW v1.4.3
  [7034ab61] FastBroadcast v0.1.8
  [9aa1b823] FastClosures v0.3.2
  [1a297f60] FillArrays v0.11.9
  [6a86dc24] FiniteDiff v2.8.1
  [f6369f11] ForwardDiff v0.10.18
  [069b7b12] FunctionWrappers v1.1.2
  [61eb1bfa] GPUCompiler v0.12.6
  [bc5e4493] GitHub v5.6.0
  [af5da776] GlobalSensitivity v1.1.0
  [cd3eb016] HTTP v0.9.12
  [0e44f5e4] Hwloc v2.0.0
  [7869d1d1] IRTools v0.4.3
  [615f187c] IfElse v0.1.0
  [d25df0c9] Inflate v0.1.2
  [83e8ac13] IniFile v0.5.0
  [a98d9a8b] Interpolations v0.13.3
  [42fd0dbc] IterativeSolvers v0.9.1
  [82899510] IteratorInterfaceExtensions v1.0.0
  [692b3bcd] JLLWrappers v1.3.0
  [682c06a0] JSON v0.21.1
  [5ab0869b] KernelDensity v0.6.3
  [929cbde3] LLVM v4.1.1
  [2ee39098] LabelledArrays v1.6.2
  [a5e1c1ea] LatinHypercubeSampling v1.8.0
  [73f95e8e] LatticeRules v0.0.1
  [093fc24a] LightGraphs v1.3.5
  [d3d80556] LineSearches v7.1.1
  [2ab3a3ac] LogExpFunctions v0.2.5
  [1914dd2f] MacroTools v0.5.6
  [d125e4d3] ManualMemory v0.1.4
  [739be429] MbedTLS v1.0.3
  [e1d29d7a] Missings v1.0.0
  [78c3b35d] Mocking v0.7.1
  [46d2c3a1] MuladdMacro v0.2.2
  [d41bc354] NLSolversBase v7.8.0
  [2774e3e8] NLsolve v4.5.1
  [872c559c] NNlib v0.7.25
  [77ba4419] NaNMath v0.3.5
  [8913a72c] NonlinearSolve v0.3.8
  [d8793406] ObjectFile v0.3.7
  [6fe1bfb0] OffsetArrays v1.10.3
  [429524aa] Optim v1.3.0
  [bac558e1] OrderedCollections v1.4.1
  [1dea7af3] OrdinaryDiffEq v5.60.1
  [90014a1f] PDMats v0.11.1
  [d96e819e] Parameters v0.12.2
  [69de0a69] Parsers v1.1.0
  [e409e4f3] PoissonRandom v0.4.0
  [f517fe37] Polyester v0.3.7
  [85a6dd25] PositiveFactorizations v0.2.4
  [21216c6a] Preferences v1.2.2
  [1fd47b50] QuadGK v2.4.1
  [8a4e6c94] QuasiMonteCarlo v0.2.3
  [74087812] Random123 v1.4.2
  [e6cf234a] RandomNumbers v1.4.0
  [c84ed2f1] Ratios v0.4.0
  [3cdcf5f2] RecipesBase v1.1.1
  [731186ca] RecursiveArrayTools v2.16.0
  [f2c3362d] RecursiveFactorization v0.1.0
  [189a3867] Reexport v1.1.0
  [ae029012] Requires v1.1.3
  [ae5879a3] ResettableStacks v1.1.1
  [37e2e3b7] ReverseDiff v1.9.0
  [79098fc4] Rmath v0.7.0
  [1bc83da4] SafeTestsets v0.0.1
  [0bca4576] SciMLBase v1.18.2
  [efcf1570] Setfield v0.7.0
  [699a6c99] SimpleTraits v0.9.4
  [ed01d8cd] Sobol v1.5.0
  [2133526b] SodiumSeal v0.1.1
  [a2af1166] SortingAlgorithms v1.0.1
  [47a9eef4] SparseDiffTools v1.15.0
  [276daf66] SpecialFunctions v1.5.1
  [860ef19b] StableRNGs v1.0.0
  [aedffcd0] Static v0.3.0
  [90137ffa] StaticArrays v1.2.7
  [82ae8749] StatsAPI v1.0.0
  [2913bbd2] StatsBase v0.33.8
  [4c63d2b9] StatsFuns v0.9.8
  [9672c7b4] SteadyStateDiffEq v1.6.4
  [789caeaf] StochasticDiffEq v6.35.0
  [7792a7ef] StrideArraysCore v0.1.17
  [53d494c1] StructIO v0.3.0
  [3783bdb8] TableTraits v1.0.1
  [bd369af6] Tables v1.4.4
  [8290d209] ThreadingUtilities v0.4.6
  [f269a46b] TimeZones v1.5.6
  [a759f4b9] TimerOutputs v0.5.12
  [9f7883ad] Tracker v0.2.16
  [592b5752] Trapz v2.0.2
  [a2a6695c] TreeViews v0.3.0
  [5c2747f8] URIs v1.3.0
  [3a884ed6] UnPack v1.0.2
  [3d5dd08c] VectorizationBase v0.20.25
  [19fa3120] VertexSafeGraphs v0.1.2
  [efce3f68] WoodburyMatrices v0.5.3
  [e88e6eb3] Zygote v0.6.17
  [700de1a5] ZygoteRules v0.2.1
  [7cc45869] Enzyme_jll v0.0.16+0
  [f5851436] FFTW_jll v3.3.9+8
  [e33a78d0] Hwloc_jll v2.5.0+0
  [1d5cc7b8] IntelOpenMP_jll v2018.0.3+2
  [dad2f222] LLVMExtra_jll v0.0.6+0
  [856f044c] MKL_jll v2021.1.1+1
  [efe28fd5] OpenSpecFun_jll v0.5.5+0
  [f50d1b31] Rmath_jll v0.3.0+0
  [a9144af2] libsodium_jll v1.0.20+0
  [0dad84c5] ArgTools `@stdlib/ArgTools`
  [56f22d72] Artifacts `@stdlib/Artifacts`
  [2a0f44e3] Base64 `@stdlib/Base64`
  [ade2ca70] Dates `@stdlib/Dates`
  [8bb1440f] DelimitedFiles `@stdlib/DelimitedFiles`
  [8ba89e20] Distributed `@stdlib/Distributed`
  [f43a241f] Downloads `@stdlib/Downloads`
  [9fa8497b] Future `@stdlib/Future`
  [b77e0a4c] InteractiveUtils `@stdlib/InteractiveUtils`
  [4af54fe1] LazyArtifacts `@stdlib/LazyArtifacts`
  [b27032c2] LibCURL `@stdlib/LibCURL`
  [76f85450] LibGit2 `@stdlib/LibGit2`
  [8f399da3] Libdl `@stdlib/Libdl`
  [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`
  [56ddb016] Logging `@stdlib/Logging`
  [d6f4376e] Markdown `@stdlib/Markdown`
  [a63ad114] Mmap `@stdlib/Mmap`
  [ca575930] NetworkOptions `@stdlib/NetworkOptions`
  [44cfe95a] Pkg `@stdlib/Pkg`
  [de0858da] Printf `@stdlib/Printf`
  [3fa0cd96] REPL `@stdlib/REPL`
  [9a3f8284] Random `@stdlib/Random`
  [ea8e919c] SHA `@stdlib/SHA`
  [9e88b42a] Serialization `@stdlib/Serialization`
  [1a1011a3] SharedArrays `@stdlib/SharedArrays`
  [6462fe0b] Sockets `@stdlib/Sockets`
  [2f01184e] SparseArrays `@stdlib/SparseArrays`
  [10745b16] Statistics `@stdlib/Statistics`
  [4607b0f0] SuiteSparse `@stdlib/SuiteSparse`
  [fa267f1f] TOML `@stdlib/TOML`
  [a4e569a6] Tar `@stdlib/Tar`
  [8dfed614] Test `@stdlib/Test`
  [cf7118a7] UUIDs `@stdlib/UUIDs`
  [4ec0a83e] Unicode `@stdlib/Unicode`
  [e66e0078] CompilerSupportLibraries_jll `@stdlib/CompilerSupportLibraries_jll`
  [deac9b47] LibCURL_jll `@stdlib/LibCURL_jll`
  [29816b5a] LibSSH2_jll `@stdlib/LibSSH2_jll`
  [c8ffd9c3] MbedTLS_jll `@stdlib/MbedTLS_jll`
  [14a3606d] MozillaCACerts_jll `@stdlib/MozillaCACerts_jll`
  [83775a58] Zlib_jll `@stdlib/Zlib_jll`
  [8e850ede] nghttp2_jll `@stdlib/nghttp2_jll`
  [3f19e933] p7zip_jll `@stdlib/p7zip_jll`
     Testing Running tests...
integrator.t = 0.45175395145262576
bounced.
integrator.t = 0.4517525836710994
bounced.
integrator.t = 0.4517553192465762
bounced.
integrator.t = 0.45175395145262576
bounced.
integrator.t = 0.45175395145262576
bounced.
integrator.t = Dual{ForwardDiff.Tag{typeof(Main.##293.test_f), Float64}}(0.4517539514526263,-0.023048670992481403,0.0)
bounced.
integrator.t = 0.45175395145262576
bounced.
integrator.t = 0.45175395145262576
bounced.
integrator.t = 0.45175395145262576
bounced.
VA[i] = [0.46893970362431764, -1.831060296375681]
integrator.t = Dual{ForwardDiff.Tag{SciMLBase.ODEFunction{true, typeof(Main.##293.f), LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing}, Float64}}(0.4517539514526258,0.22587697572631502,0.10204081632653147)
bounced.
integrator.t = Dual{ForwardDiff.Tag{SciMLBase.ODEFunction{true, typeof(Main.##293.f), LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing}, Float64}}(0.4517539514526263,-0.023048670992481403,0.0)
bounced.
integrator.t = TrackedReal<8uV>(0.4517539514526256, 0.0, D2L, ---)
bounced.
integrator.t = TrackedReal<CBY>(0.45175395145262576, 0.0, 2Za, ---)
bounced.
integrator.t = TrackedReal<2S0>(0.4517539514526256, 0.0, 5fW, ---)
bounced.
integrator.t = TrackedReal<HzQ>(0.4517539514526256, 0.0, DKm, ---)
bounced.
integrator.t = 0.4517539514526256
bounced.
VA[i] = [0.4689397036243164, -1.831060296375684]
integrator.t = Dual{ForwardDiff.Tag{SciMLBase.ODEFunction{true, typeof(Main.##293.f), LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing}, Float64}}(0.4517539514526256,0.225876975726313,0.10204081632653056)
bounced.
integrator.t = Dual{ForwardDiff.Tag{SciMLBase.ODEFunction{true, typeof(Main.##293.f), LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing}, Float64}}(0.4517539514526256,-0.023048670992480785,0.0)
bounced.
Test Summary:   | Pass  Broken  Total
Autodiff Events |    7       4     11
256.038556 seconds (485.85 M allocations: 30.254 GiB, 4.46% gc time, 0.05% compilation time)
256.097329 seconds (485.91 M allocations: 30.258 GiB, 4.46% gc time, 0.05% compilation time)
     Testing DiffEqSensitivity tests passed 
```

For completeness: This is the original print out 
```
frank@phys-cmt-42:~/.julia/dev/DiffEqSensitivity$ julia --project=. -e 'using Pkg; Pkg.resolve(); Pkg.test()'
  No Changes to `~/.julia/dev/DiffEqSensitivity/Project.toml`
  No Changes to `~/.julia/dev/DiffEqSensitivity/Manifest.toml`
     Testing DiffEqSensitivity
      Status `/tmp/jl_xiIqB7/Project.toml`
  [79e6a3ab] Adapt v3.3.1
  [2169fc97] AlgebraicMultigrid v0.4.0
  [4fba245c] ArrayInterface v3.1.18
  [49dc2e85] Calculus v0.5.1
  [7057c7e9] Cassette v0.3.7
  [d360d2e6] ChainRulesCore v0.10.13
  [b0b7db55] ComponentArrays v0.11.1
  [2b5f629d] DiffEqBase v6.69.1
  [459566f4] DiffEqCallbacks v2.16.1
  [77a26b50] DiffEqNoiseProcess v5.9.0
  [41bf760c] DiffEqSensitivity v6.55.3 `~/.julia/dev/DiffEqSensitivity`
  [b552c78f] DiffRules v1.0.2
  [31c24e10] Distributions v0.25.11
  [7da242da] Enzyme v0.7.0
  [7a1cc6ca] FFTW v1.4.3
  [6a86dc24] FiniteDiff v2.8.1
  [f6369f11] ForwardDiff v0.10.18
  [af5da776] GlobalSensitivity v1.1.0
  [2774e3e8] NLsolve v4.5.1
  [1dea7af3] OrdinaryDiffEq v5.55.1
  [d96e819e] Parameters v0.12.2
  [1fd47b50] QuadGK v2.4.1
  [8a4e6c94] QuasiMonteCarlo v0.2.3
  [e6cf234a] RandomNumbers v1.4.0
  [731186ca] RecursiveArrayTools v2.16.0
  [189a3867] Reexport v1.1.0
  [ae029012] Requires v1.1.3
  [37e2e3b7] ReverseDiff v1.9.0
  [1bc83da4] SafeTestsets v0.0.1
  [9672c7b4] SteadyStateDiffEq v1.6.4
  [789caeaf] StochasticDiffEq v6.35.0
  [9f7883ad] Tracker v0.2.16
  [e88e6eb3] Zygote v0.6.17
  [700de1a5] ZygoteRules v0.2.1
  [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`
  [44cfe95a] Pkg `@stdlib/Pkg`
  [9a3f8284] Random `@stdlib/Random`
  [1a1011a3] SharedArrays `@stdlib/SharedArrays`
  [2f01184e] SparseArrays `@stdlib/SparseArrays`
  [10745b16] Statistics `@stdlib/Statistics`
  [8dfed614] Test `@stdlib/Test`
      Status `/tmp/jl_xiIqB7/Manifest.toml`
  [621f4979] AbstractFFTs v1.0.1
  [79e6a3ab] Adapt v3.3.1
  [2169fc97] AlgebraicMultigrid v0.4.0
  [ec485272] ArnoldiMethod v0.1.0
  [4fba245c] ArrayInterface v3.1.18
  [13072b0f] AxisAlgorithms v1.0.0
  [fa961155] CEnum v0.4.1
  [49dc2e85] Calculus v0.5.1
  [7057c7e9] Cassette v0.3.7
  [082447d4] ChainRules v0.8.23
  [d360d2e6] ChainRulesCore v0.10.13
  [38540f10] CommonSolve v0.2.0
  [bbf7d656] CommonSubexpressions v0.3.0
  [34da2185] Compat v3.31.0
  [aa819f21] CompatHelper v1.18.6
  [b0b7db55] ComponentArrays v0.11.1
  [187b0558] ConstructionBase v1.3.0
  [9a962f9c] DataAPI v1.7.0
  [864edb3b] DataStructures v0.18.9
  [e2d170a0] DataValueInterfaces v1.0.0
  [2b5f629d] DiffEqBase v6.69.1
  [459566f4] DiffEqCallbacks v2.16.1
  [c894b116] DiffEqJump v6.15.1
  [77a26b50] DiffEqNoiseProcess v5.9.0
  [41bf760c] DiffEqSensitivity v6.55.3 `~/.julia/dev/DiffEqSensitivity`
  [163ba53b] DiffResults v1.0.3
  [b552c78f] DiffRules v1.0.2
  [b4f34e82] Distances v0.10.3
  [31c24e10] Distributions v0.25.11
  [ffbed154] DocStringExtensions v0.8.5
  [7da242da] Enzyme v0.7.0
  [d4d017d3] ExponentialUtilities v1.8.4
  [e2ba6199] ExprTools v0.1.6
  [7a1cc6ca] FFTW v1.4.3
  [7034ab61] FastBroadcast v0.1.8
  [9aa1b823] FastClosures v0.3.2
  [1a297f60] FillArrays v0.11.9
  [6a86dc24] FiniteDiff v2.8.1
  [f6369f11] ForwardDiff v0.10.18
  [069b7b12] FunctionWrappers v1.1.2
  [61eb1bfa] GPUCompiler v0.12.6
  [bc5e4493] GitHub v5.6.0
  [af5da776] GlobalSensitivity v1.1.0
  [cd3eb016] HTTP v0.9.12
  [7869d1d1] IRTools v0.4.3
  [615f187c] IfElse v0.1.0
  [d25df0c9] Inflate v0.1.2
  [83e8ac13] IniFile v0.5.0
  [a98d9a8b] Interpolations v0.13.3
  [42fd0dbc] IterativeSolvers v0.9.1
  [82899510] IteratorInterfaceExtensions v1.0.0
  [692b3bcd] JLLWrappers v1.3.0
  [682c06a0] JSON v0.21.1
  [5ab0869b] KernelDensity v0.6.3
  [929cbde3] LLVM v4.1.1
  [2ee39098] LabelledArrays v1.6.2
  [a5e1c1ea] LatinHypercubeSampling v1.8.0
  [73f95e8e] LatticeRules v0.0.1
  [093fc24a] LightGraphs v1.3.5
  [d3d80556] LineSearches v7.1.1
  [2ab3a3ac] LogExpFunctions v0.2.5
  [1914dd2f] MacroTools v0.5.6
  [739be429] MbedTLS v1.0.3
  [e1d29d7a] Missings v1.0.0
  [78c3b35d] Mocking v0.7.1
  [46d2c3a1] MuladdMacro v0.2.2
  [d41bc354] NLSolversBase v7.8.0
  [2774e3e8] NLsolve v4.5.1
  [872c559c] NNlib v0.7.25
  [77ba4419] NaNMath v0.3.5
  [8913a72c] NonlinearSolve v0.3.8
  [d8793406] ObjectFile v0.3.7
  [6fe1bfb0] OffsetArrays v1.10.3
  [429524aa] Optim v1.3.0
  [bac558e1] OrderedCollections v1.4.1
  [1dea7af3] OrdinaryDiffEq v5.55.1
  [90014a1f] PDMats v0.11.1
  [d96e819e] Parameters v0.12.2
  [69de0a69] Parsers v1.1.0
  [e409e4f3] PoissonRandom v0.4.0
  [85a6dd25] PositiveFactorizations v0.2.4
  [21216c6a] Preferences v1.2.2
  [1fd47b50] QuadGK v2.4.1
  [8a4e6c94] QuasiMonteCarlo v0.2.3
  [74087812] Random123 v1.4.2
  [e6cf234a] RandomNumbers v1.4.0
  [c84ed2f1] Ratios v0.4.0
  [3cdcf5f2] RecipesBase v1.1.1
  [731186ca] RecursiveArrayTools v2.16.0
  [f2c3362d] RecursiveFactorization v0.1.0
  [189a3867] Reexport v1.1.0
  [ae029012] Requires v1.1.3
  [ae5879a3] ResettableStacks v1.1.1
  [37e2e3b7] ReverseDiff v1.9.0
  [79098fc4] Rmath v0.7.0
  [1bc83da4] SafeTestsets v0.0.1
  [0bca4576] SciMLBase v1.18.2
  [efcf1570] Setfield v0.7.0
  [699a6c99] SimpleTraits v0.9.4
  [ed01d8cd] Sobol v1.5.0
  [2133526b] SodiumSeal v0.1.1
  [a2af1166] SortingAlgorithms v1.0.1
  [47a9eef4] SparseDiffTools v1.15.0
  [276daf66] SpecialFunctions v1.5.1
  [860ef19b] StableRNGs v1.0.0
  [aedffcd0] Static v0.3.0
  [90137ffa] StaticArrays v1.2.7
  [82ae8749] StatsAPI v1.0.0
  [2913bbd2] StatsBase v0.33.8
  [4c63d2b9] StatsFuns v0.9.8
  [9672c7b4] SteadyStateDiffEq v1.6.4
  [789caeaf] StochasticDiffEq v6.35.0
  [53d494c1] StructIO v0.3.0
  [3783bdb8] TableTraits v1.0.1
  [bd369af6] Tables v1.4.4
  [f269a46b] TimeZones v1.5.6
  [a759f4b9] TimerOutputs v0.5.12
  [9f7883ad] Tracker v0.2.16
  [592b5752] Trapz v2.0.2
  [a2a6695c] TreeViews v0.3.0
  [5c2747f8] URIs v1.3.0
  [3a884ed6] UnPack v1.0.2
  [19fa3120] VertexSafeGraphs v0.1.2
  [efce3f68] WoodburyMatrices v0.5.3
  [e88e6eb3] Zygote v0.6.17
  [700de1a5] ZygoteRules v0.2.1
  [7cc45869] Enzyme_jll v0.0.16+0
  [f5851436] FFTW_jll v3.3.9+8
  [1d5cc7b8] IntelOpenMP_jll v2018.0.3+2
  [dad2f222] LLVMExtra_jll v0.0.6+0
  [856f044c] MKL_jll v2021.1.1+1
  [efe28fd5] OpenSpecFun_jll v0.5.5+0
  [f50d1b31] Rmath_jll v0.3.0+0
  [a9144af2] libsodium_jll v1.0.20+0
  [0dad84c5] ArgTools `@stdlib/ArgTools`
  [56f22d72] Artifacts `@stdlib/Artifacts`
  [2a0f44e3] Base64 `@stdlib/Base64`
  [ade2ca70] Dates `@stdlib/Dates`
  [8bb1440f] DelimitedFiles `@stdlib/DelimitedFiles`
  [8ba89e20] Distributed `@stdlib/Distributed`
  [f43a241f] Downloads `@stdlib/Downloads`
  [9fa8497b] Future `@stdlib/Future`
  [b77e0a4c] InteractiveUtils `@stdlib/InteractiveUtils`
  [4af54fe1] LazyArtifacts `@stdlib/LazyArtifacts`
  [b27032c2] LibCURL `@stdlib/LibCURL`
  [76f85450] LibGit2 `@stdlib/LibGit2`
  [8f399da3] Libdl `@stdlib/Libdl`
  [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`
  [56ddb016] Logging `@stdlib/Logging`
  [d6f4376e] Markdown `@stdlib/Markdown`
  [a63ad114] Mmap `@stdlib/Mmap`
  [ca575930] NetworkOptions `@stdlib/NetworkOptions`
  [44cfe95a] Pkg `@stdlib/Pkg`
  [de0858da] Printf `@stdlib/Printf`
  [3fa0cd96] REPL `@stdlib/REPL`
  [9a3f8284] Random `@stdlib/Random`
  [ea8e919c] SHA `@stdlib/SHA`
  [9e88b42a] Serialization `@stdlib/Serialization`
  [1a1011a3] SharedArrays `@stdlib/SharedArrays`
  [6462fe0b] Sockets `@stdlib/Sockets`
  [2f01184e] SparseArrays `@stdlib/SparseArrays`
  [10745b16] Statistics `@stdlib/Statistics`
  [4607b0f0] SuiteSparse `@stdlib/SuiteSparse`
  [fa267f1f] TOML `@stdlib/TOML`
  [a4e569a6] Tar `@stdlib/Tar`
  [8dfed614] Test `@stdlib/Test`
  [cf7118a7] UUIDs `@stdlib/UUIDs`
  [4ec0a83e] Unicode `@stdlib/Unicode`
  [e66e0078] CompilerSupportLibraries_jll `@stdlib/CompilerSupportLibraries_jll`
  [deac9b47] LibCURL_jll `@stdlib/LibCURL_jll`
  [29816b5a] LibSSH2_jll `@stdlib/LibSSH2_jll`
  [c8ffd9c3] MbedTLS_jll `@stdlib/MbedTLS_jll`
  [14a3606d] MozillaCACerts_jll `@stdlib/MozillaCACerts_jll`
  [83775a58] Zlib_jll `@stdlib/Zlib_jll`
  [8e850ede] nghttp2_jll `@stdlib/nghttp2_jll`
  [3f19e933] p7zip_jll `@stdlib/p7zip_jll`
     Testing Running tests...
integrator.t = 0.45175395145262576
bounced.
integrator.t = 0.4517525836710994
bounced.
integrator.t = 0.4517553192465762
bounced.
integrator.t = 0.45175395145262576
bounced.
integrator.t = 0.45175395145262576
bounced.
integrator.t = Dual{ForwardDiff.Tag{typeof(Main.##293.test_f), Float64}}(0.4517539514526263,-0.023048670992481403,0.0)
bounced.
integrator.t = 0.45175395145262576
bounced.
integrator.t = 0.45175395145262576
bounced.
integrator.t = 0.45175395145262576
bounced.
VA[i] = [0.46893970362431764, -1.831060296375681]
integrator.t = Dual{ForwardDiff.Tag{SciMLBase.ODEFunction{true, typeof(Main.##293.f), LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing}, Float64}}(0.4517539514526258,0.22587697572631502,0.10204081632653147)
bounced.
integrator.t = Dual{ForwardDiff.Tag{SciMLBase.ODEFunction{true, typeof(Main.##293.f), LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing}, Float64}}(0.4517539514526263,-0.023048670992481403,0.0)
bounced.
Autodiff Events: Error During Test at /home/frank/.julia/packages/SafeTestsets/A83XK/src/SafeTestsets.jl:25
  Got exception outside of a @test
  LoadError: ArgumentError: Converting an instance of ReverseDiff.TrackedReal{Float64, Float64, Nothing} to Float32 is not defined. Please use `ReverseDiff.value` instead.
  Stacktrace: ...
```

**Pull request merged**
