### PR TITLE
test ChainRules 1

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Held back by https://github.com/TuringLang/DistributionsAD.jl/pull/184

**Comment by DhairyaLGandhi** [comment]
I think @oxinabox  is tracking the changes in CR 1 that broke the tests here.

**Comment by oxinabox** [comment]
I am. Though my time for digging into them is limited. I hope to have time next week.

I agree it probably was not a new change, in ChainRulesCore or in Zygote.
It might have been a new rule in ChainRules, exposing a underlying problem in the Zygote-ChainRules interface.
Or just that the Zygote tests hadn't been run in so long.

**Comment by ChrisRackauckas** [comment]
Awesome.

**Pull request closed without merging**
