### PR TITLE
Handle the NoTangents produced by Zygote v6.23

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by bolognam** [comment]
Hey @ChrisRackauckas can this PR get merged (after CI gets fixed)? I want to work on DiffEqFlux.jl soon.

**Comment by ChrisRackauckas** [comment]
It's most likely not necessary because of https://github.com/SciML/RecursiveArrayTools.jl

**Comment by bolognam** [comment]
@ChrisRackauckas Got it, then I just need a new release for DiffEqSensitivity.jl because the last release doesn't have the compat entry for v1 of ChainRulesCore.jl (and I get issues trying to add DiffEqSensitivity.jl with MTK in my `Project.toml`)

**Comment by ChrisRackauckas** [comment]
Alright, some stuff here was needed

**Pull request merged**
