### PR TITLE
see if test failure is only shadowing

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
@frankschae confirmed it's only shadowing and callbacks.

**Comment by ChrisRackauckas** [comment]
@frankschae can you look into the callback tests?

**Comment by frankschae** [comment]
yup, I anyways also wanted to look again into #507. Did we merge anything that changed saving behavior?

**Comment by frankschae** [comment]
I can reproduce it locally by running
```julia
julia --project=. -e 'using Pkg; Pkg.instantiate(); Pkg.test()'
```
However, when I just add the packages from `using`
```julia
  [41bf760c] DiffEqSensitivity v6.66.0 `~/.julia/dev/DiffEqSensitivity`
  [f6369f11] ForwardDiff v0.10.24
  [1dea7af3] OrdinaryDiffEq v6.0.3
  [789caeaf] StochasticDiffEq v6.43.0
  [e88e6eb3] Zygote v0.6.33
``` 
I don't observe the test failure.
The test failure only occurs for `InterpolatingAdjoint(checkpointing=true)`.
@ChrisRackauckas does the output of the Manifests tell you something? 

```diff text.txt text2.txt 
1c1
<   [621f4979] AbstractFFTs v1.0.1
---
> [621f4979] AbstractFFTs v1.0.1
4d3
<   [2169fc97] AlgebraicMultigrid v0.4.2
21d19
<   [49dc2e85] Calculus v0.5.1
32,33d29
<   [aa819f21] CompatHelper v3.1.0
<   [b0b7db55] ComponentArrays v0.11.7
70d65
<   [8f6bce27] GitForge v0.2.8
73d67
<   [cd3eb016] HTTP v0.9.17
79d72
<   [83e8ac13] IniFile v0.5.0
81d73
<   [842dd82b] InlineStrings v1.1.1
90d81
<   [2535ab7d] JSON2 v0.3.4
112d102
<   [739be429] MbedTLS v1.0.3
116d105
<   [78c3b35d] Mocking v0.7.3
119d107
<   [1e8d2bf6] MultilineStrings v0.1.1
175d162
<   [9672c7b4] SteadyStateDiffEq v1.6.6
186d172
<   [f269a46b] TimeZones v1.7.0
210,255c196,241
<   [0dad84c5] ArgTools `@stdlib/ArgTools`
<   [56f22d72] Artifacts `@stdlib/Artifacts`
<   [2a0f44e3] Base64 `@stdlib/Base64`
<   [ade2ca70] Dates `@stdlib/Dates`
<   [8bb1440f] DelimitedFiles `@stdlib/DelimitedFiles`
<   [8ba89e20] Distributed `@stdlib/Distributed`
<   [f43a241f] Downloads `@stdlib/Downloads`
<   [9fa8497b] Future `@stdlib/Future`
<   [b77e0a4c] InteractiveUtils `@stdlib/InteractiveUtils`
<   [4af54fe1] LazyArtifacts `@stdlib/LazyArtifacts`
<   [b27032c2] LibCURL `@stdlib/LibCURL`
<   [76f85450] LibGit2 `@stdlib/LibGit2`
<   [8f399da3] Libdl `@stdlib/Libdl`
<   [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`
<   [56ddb016] Logging `@stdlib/Logging`
<   [d6f4376e] Markdown `@stdlib/Markdown`
<   [a63ad114] Mmap `@stdlib/Mmap`
<   [ca575930] NetworkOptions `@stdlib/NetworkOptions`
<   [44cfe95a] Pkg `@stdlib/Pkg`
<   [de0858da] Printf `@stdlib/Printf`
<   [3fa0cd96] REPL `@stdlib/REPL`
<   [9a3f8284] Random `@stdlib/Random`
<   [ea8e919c] SHA `@stdlib/SHA`
<   [9e88b42a] Serialization `@stdlib/Serialization`
<   [1a1011a3] SharedArrays `@stdlib/SharedArrays`
<   [6462fe0b] Sockets `@stdlib/Sockets`
<   [2f01184e] SparseArrays `@stdlib/SparseArrays`
<   [10745b16] Statistics `@stdlib/Statistics`
<   [4607b0f0] SuiteSparse `@stdlib/SuiteSparse`
<   [fa267f1f] TOML `@stdlib/TOML`
<   [a4e569a6] Tar `@stdlib/Tar`
<   [8dfed614] Test `@stdlib/Test`
<   [cf7118a7] UUIDs `@stdlib/UUIDs`
<   [4ec0a83e] Unicode `@stdlib/Unicode`
<   [e66e0078] CompilerSupportLibraries_jll `@stdlib/CompilerSupportLibraries_jll`
<   [deac9b47] LibCURL_jll `@stdlib/LibCURL_jll`
<   [29816b5a] LibSSH2_jll `@stdlib/LibSSH2_jll`
<   [c8ffd9c3] MbedTLS_jll `@stdlib/MbedTLS_jll`
<   [14a3606d] MozillaCACerts_jll `@stdlib/MozillaCACerts_jll`
<   [4536629a] OpenBLAS_jll `@stdlib/OpenBLAS_jll`
<   [05823500] OpenLibm_jll `@stdlib/OpenLibm_jll`
<   [bea87d4a] SuiteSparse_jll `@stdlib/SuiteSparse_jll`
<   [83775a58] Zlib_jll `@stdlib/Zlib_jll`
<   [8e850b90] libblastrampoline_jll `@stdlib/libblastrampoline_jll`
<   [8e850ede] nghttp2_jll `@stdlib/nghttp2_jll`
<   [3f19e933] p7zip_jll `@stdlib/p7zip_jll`
---
>   [0dad84c5] ArgTools
>   [56f22d72] Artifacts
>   [2a0f44e3] Base64
>   [ade2ca70] Dates
>   [8bb1440f] DelimitedFiles
>   [8ba89e20] Distributed
>   [f43a241f] Downloads
>   [9fa8497b] Future
>   [b77e0a4c] InteractiveUtils
>   [4af54fe1] LazyArtifacts
>   [b27032c2] LibCURL
>   [76f85450] LibGit2
>   [8f399da3] Libdl
>   [37e2e46d] LinearAlgebra
>   [56ddb016] Logging
>   [d6f4376e] Markdown
>   [a63ad114] Mmap
>   [ca575930] NetworkOptions
>   [44cfe95a] Pkg
>   [de0858da] Printf
>   [3fa0cd96] REPL
>   [9a3f8284] Random
>   [ea8e919c] SHA
>   [9e88b42a] Serialization
>   [1a1011a3] SharedArrays
>   [6462fe0b] Sockets
>   [2f01184e] SparseArrays
>   [10745b16] Statistics
>   [4607b0f0] SuiteSparse
>   [fa267f1f] TOML
>   [a4e569a6] Tar
>   [8dfed614] Test
>   [cf7118a7] UUIDs
>   [4ec0a83e] Unicode
>   [e66e0078] CompilerSupportLibraries_jll
>   [deac9b47] LibCURL_jll
>   [29816b5a] LibSSH2_jll
>   [c8ffd9c3] MbedTLS_jll
>   [14a3606d] MozillaCACerts_jll
>   [4536629a] OpenBLAS_jll
>   [05823500] OpenLibm_jll
>   [bea87d4a] SuiteSparse_jll
>   [83775a58] Zlib_jll
>   [8e850b90] libblastrampoline_jll
>   [8e850ede] nghttp2_jll
>   [3f19e933] p7zip_jll
```

**Comment by ChrisRackauckas** [comment]
No, I'm at a loss. So it's only with checkpointing? That's really odd. Maybe some initialization is bad? Try a different ODE solver, maybe one without special interpolations?

**Comment by frankschae** [comment]
Yup, it's only `du3` and `dp3` for continuous callbacks with InterpolatingAdjoint + checkpointing (all the others are fine):
https://github.com/SciML/DiffEqSensitivity.jl/blob/6d653fc3f0d8f27fdab7e5d29b39338aeef4ff1b/test/callbacks.jl#L309-L311

> Try a different ODE solver, maybe one without special interpolations?
sounds good. I'll play around a bit.

**Pull request merged**
