### PR TITLE
Fix the enzyme default check

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
```julia
using OrdinaryDiffEq, Zygote, DiffEqSensitivity
function fiip(du,u,p,t)
  du[1] = dx = p[1]*u[1] - p[2]*u[1]*u[2]
  du[2] = dy = -p[3]*u[2] + p[4]*u[1]*u[2]
end
p = [1.5,1.0,3.0,1.0]; u0 = [1.0; 1.0]
prob = ODEProblem(fiip,complex(u0),(0.0,10.0),complex(p))

function sum_of_solution(u0, p)
    _prob = remake(prob,u0=u0,p=p)
    real(sum(solve(_prob,Tsit5(),reltol=1e-6,abstol=1e-6,saveat=0.1)))
end

dx = Zygote.gradient(sum_of_solution, complex(u0), complex(p))
```

now works.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
It looks like Zygote on v1.7 is missing derivatives for gemv! coming from some higher level vector math call? @maleadt @DhairyaLGandhi I'm going to merge and ignore this but that's a little odd.

https://buildkite.com/julialang/diffeqsensitivity-dot-jl/builds/510#ac82ea28-d297-45b5-bb5f-01f490e5759d/668-1284

**Comment by DhairyaLGandhi** [comment]
Seems to be a matrix-vector-scalar call somewhere in cublas. @maleadt is there a change in the code path for CUDA in 1.7?

**Comment by maleadt** [comment]
Nothing comes to mind, no.

**Comment by devmotion** [comment]
The seemingly same error showed up also in ApproximateGPs (https://github.com/JuliaGaussianProcesses/ApproximateGPs.jl/runs/4385202539?check_suite_focus=true#step:5:31, the corresponding issue is https://github.com/JuliaGaussianProcesses/ApproximateGPs.jl/issues/82). Since the package and its tutorials don't use CUDA, it seems to be a more general BLAS/Zygote issue.

**Pull request merged**
